CC=gcc
CFLAGS=-std=gnu99 -Wall

all: etap1 etap2 etap3

etap3: etap3.c
	$(CC) $(CFLAGS) -o etap3 etap3.c

etap2: etap2.c
	$(CC) $(CFLAGS) -o etap2 etap2.c

etap1: etap1.c
	$(CC) $(CFLAGS) -o etap1 etap1.c

clean:
	rm -f etap1 etap2 etap3